import {
  Building2,
  Truck,
  Package,
  Warehouse,
  Ruler,
  Percent,
  CreditCard,
  Receipt,
  Tags,
  Coins,
  GitBranch,
  UserRound,
} from "lucide-react";
import type { MasterDef } from "./types";

export const MASTERS: MasterDef[] = [
  {
    key: "customers",
    label: "Customers",
    singular: "customer",
    description: "Companies you sell to.",
    icon: Building2,
    table: "customers",
    nameField: "name",
    orderBy: "name",
    editorRoles: ["sales"],
    fields: [
      { key: "name", label: "Name", type: "text", required: true, showInList: true, showInExport: true, span: 2 },
      { key: "contact_person", label: "Contact person", type: "text", showInList: true, showInExport: true },
      { key: "email", label: "Email", type: "email", showInList: true, showInExport: true },
      { key: "phone", label: "Phone", type: "phone", showInList: true, showInExport: true },
      { key: "gst_number", label: "GST Number", type: "text", uppercase: true, showInList: true, showInExport: true },
      { key: "state_code", label: "State code", type: "text", showInList: true, showInExport: true },
      { key: "billing_address", label: "Billing address", type: "textarea", span: 2, showInExport: true },
      { key: "shipping_address", label: "Shipping address", type: "textarea", span: 2, showInExport: true },
      { key: "is_active", label: "Active", type: "boolean", defaultValue: true, showInList: true, showInExport: true },
    ],
    filters: [
      { key: "is_active", label: "Status", options: [ { value: "true", label: "Active" }, { value: "false", label: "Inactive" } ] },
    ],
  },
  {
    key: "vendors",
    label: "Vendors",
    singular: "vendor",
    description: "Suppliers and service providers.",
    icon: Truck,
    table: "suppliers",
    nameField: "name",
    orderBy: "name",
    editorRoles: ["procurement"],
    fields: [
      { key: "name", label: "Name", type: "text", required: true, showInList: true, showInExport: true, span: 2 },
      { key: "contact_person", label: "Contact person", type: "text", showInList: true, showInExport: true },
      { key: "email", label: "Email", type: "email", showInList: true, showInExport: true },
      { key: "phone", label: "Phone", type: "phone", showInList: true, showInExport: true },
      { key: "gst_number", label: "GST Number", type: "text", uppercase: true, showInList: true, showInExport: true },
      { key: "state_code", label: "State code", type: "text", showInList: true, showInExport: true },
      { key: "billing_address", label: "Address", type: "textarea", span: 2, showInExport: true },
      { key: "is_active", label: "Active", type: "boolean", defaultValue: true, showInList: true, showInExport: true },
    ],
  },
  {
    key: "items",
    label: "Items",
    singular: "item",
    description: "Products, materials and services.",
    icon: Package,
    table: "items",
    nameField: "name",
    orderBy: "name",
    editorRoles: ["procurement", "inventory", "warehouse", "sales"],
    fields: [
      { key: "sku", label: "SKU", type: "text", required: true, uppercase: true, showInList: true, showInExport: true },
      { key: "name", label: "Name", type: "text", required: true, showInList: true, showInExport: true, span: 2 },
      { key: "item_type", label: "Type", type: "select", options: [
        { value: "raw_material", label: "Raw material" },
        { value: "finished_good", label: "Finished good" },
        { value: "consumable", label: "Consumable" },
        { value: "service", label: "Service" },
      ], defaultValue: "raw_material", showInList: true, showInExport: true },
      { key: "uom", label: "UOM", type: "text", defaultValue: "PCS", showInList: true, showInExport: true },
      { key: "hsn_code", label: "HSN", type: "text", showInList: true, showInExport: true },
      { key: "tax_rate", label: "Tax %", type: "number", defaultValue: 18, showInList: true, showInExport: true },
      { key: "unit_price", label: "Unit price", type: "number", defaultValue: 0, showInList: true, showInExport: true },
      { key: "reorder_level", label: "Reorder level", type: "number", defaultValue: 0, showInExport: true },
      { key: "is_active", label: "Active", type: "boolean", defaultValue: true, showInList: true, showInExport: true },
    ],
    filters: [
      { key: "item_type", label: "Type", options: [
        { value: "raw_material", label: "Raw material" },
        { value: "finished_good", label: "Finished good" },
        { value: "consumable", label: "Consumable" },
        { value: "service", label: "Service" },
      ] },
      { key: "is_active", label: "Status", options: [ { value: "true", label: "Active" }, { value: "false", label: "Inactive" } ] },
    ],
  },
  {
    key: "warehouses",
    label: "Warehouses",
    singular: "warehouse",
    description: "Physical or logical stock locations.",
    icon: Warehouse,
    table: "warehouses",
    nameField: "name",
    orderBy: "name",
    editorRoles: ["procurement", "warehouse", "inventory"],
    fields: [
      { key: "code", label: "Code", type: "text", required: true, uppercase: true, showInList: true, showInExport: true },
      { key: "name", label: "Name", type: "text", required: true, showInList: true, showInExport: true },
      { key: "address", label: "Address", type: "textarea", span: 2, showInList: true, showInExport: true },
      { key: "is_active", label: "Active", type: "boolean", defaultValue: true, showInList: true, showInExport: true },
    ],
  },
  {
    key: "uom",
    label: "UOM",
    singular: "unit of measure",
    description: "Units of measure used across items.",
    icon: Ruler,
    table: "uom",
    nameField: "name",
    orderBy: "code",
    fields: [
      { key: "code", label: "Code", type: "text", required: true, uppercase: true, showInList: true, showInExport: true },
      { key: "name", label: "Name", type: "text", required: true, showInList: true, showInExport: true },
      { key: "description", label: "Description", type: "textarea", span: 2, showInExport: true },
      { key: "is_active", label: "Active", type: "boolean", defaultValue: true, showInList: true, showInExport: true },
    ],
  },
  {
    key: "gst-rates",
    label: "GST Rates",
    singular: "GST rate",
    description: "GST slabs with CGST / SGST / IGST breakup.",
    icon: Percent,
    table: "gst_rates",
    nameField: "name",
    orderBy: "rate",
    editorRoles: ["finance"],
    fields: [
      { key: "name", label: "Name", type: "text", required: true, showInList: true, showInExport: true },
      { key: "rate", label: "Total rate %", type: "number", required: true, showInList: true, showInExport: true },
      { key: "cgst", label: "CGST %", type: "number", defaultValue: 0, showInList: true, showInExport: true },
      { key: "sgst", label: "SGST %", type: "number", defaultValue: 0, showInList: true, showInExport: true },
      { key: "igst", label: "IGST %", type: "number", defaultValue: 0, showInList: true, showInExport: true },
      { key: "hsn_sac", label: "HSN / SAC", type: "text", showInList: true, showInExport: true },
      { key: "is_active", label: "Active", type: "boolean", defaultValue: true, showInList: true, showInExport: true },
    ],
  },
  {
    key: "payment-terms",
    label: "Payment Terms",
    singular: "payment term",
    description: "Credit terms used on sales and purchase documents.",
    icon: CreditCard,
    table: "payment_terms",
    nameField: "name",
    orderBy: "net_days",
    editorRoles: ["finance", "sales", "procurement"],
    fields: [
      { key: "code", label: "Code", type: "text", required: true, uppercase: true, showInList: true, showInExport: true },
      { key: "name", label: "Name", type: "text", required: true, showInList: true, showInExport: true },
      { key: "net_days", label: "Net days", type: "number", defaultValue: 30, showInList: true, showInExport: true },
      { key: "discount_percent", label: "Discount %", type: "number", defaultValue: 0, showInList: true, showInExport: true },
      { key: "discount_days", label: "Discount days", type: "number", defaultValue: 0, showInList: true, showInExport: true },
      { key: "description", label: "Description", type: "textarea", span: 2, showInExport: true },
      { key: "is_active", label: "Active", type: "boolean", defaultValue: true, showInList: true, showInExport: true },
    ],
  },
  {
    key: "tax-codes",
    label: "Tax Codes",
    singular: "tax code",
    description: "Reusable tax identifiers for GST, TDS, TCS and cesses.",
    icon: Receipt,
    table: "tax_codes",
    nameField: "name",
    orderBy: "code",
    editorRoles: ["finance"],
    fields: [
      { key: "code", label: "Code", type: "text", required: true, uppercase: true, showInList: true, showInExport: true },
      { key: "name", label: "Name", type: "text", required: true, showInList: true, showInExport: true },
      { key: "tax_type", label: "Type", type: "select", options: [
        { value: "gst", label: "GST" },
        { value: "tds", label: "TDS" },
        { value: "tcs", label: "TCS" },
        { value: "cess", label: "Cess" },
      ], defaultValue: "gst", showInList: true, showInExport: true },
      { key: "rate", label: "Rate %", type: "number", defaultValue: 0, showInList: true, showInExport: true },
      { key: "description", label: "Description", type: "textarea", span: 2, showInExport: true },
      { key: "is_active", label: "Active", type: "boolean", defaultValue: true, showInList: true, showInExport: true },
    ],
    filters: [
      { key: "tax_type", label: "Type", options: [
        { value: "gst", label: "GST" },
        { value: "tds", label: "TDS" },
        { value: "tcs", label: "TCS" },
        { value: "cess", label: "Cess" },
      ] },
    ],
  },
  {
    key: "price-lists",
    label: "Price Lists",
    singular: "price list",
    description: "Sales and purchase price catalogs.",
    icon: Tags,
    table: "price_lists",
    nameField: "name",
    orderBy: "name",
    editorRoles: ["sales", "procurement", "finance"],
    fields: [
      { key: "code", label: "Code", type: "text", required: true, uppercase: true, showInList: true, showInExport: true },
      { key: "name", label: "Name", type: "text", required: true, showInList: true, showInExport: true },
      { key: "list_type", label: "Type", type: "select", options: [
        { value: "sales", label: "Sales" },
        { value: "purchase", label: "Purchase" },
      ], defaultValue: "sales", showInList: true, showInExport: true },
      { key: "currency", label: "Currency", type: "text", defaultValue: "INR", showInList: true, showInExport: true },
      { key: "valid_from", label: "Valid from", type: "date", showInList: true, showInExport: true },
      { key: "valid_to", label: "Valid to", type: "date", showInList: true, showInExport: true },
      { key: "is_active", label: "Active", type: "boolean", defaultValue: true, showInList: true, showInExport: true },
    ],
  },
  {
    key: "currencies",
    label: "Currencies",
    singular: "currency",
    description: "Currencies and exchange rates.",
    icon: Coins,
    table: "currencies",
    nameField: "code",
    orderBy: "code",
    editorRoles: ["finance"],
    fields: [
      { key: "code", label: "Code", type: "text", required: true, uppercase: true, showInList: true, showInExport: true },
      { key: "name", label: "Name", type: "text", required: true, showInList: true, showInExport: true },
      { key: "symbol", label: "Symbol", type: "text", showInList: true, showInExport: true },
      { key: "exchange_rate", label: "Exchange rate", type: "number", defaultValue: 1, showInList: true, showInExport: true },
      { key: "is_base", label: "Base currency", type: "boolean", defaultValue: false, showInList: true, showInExport: true },
      { key: "is_active", label: "Active", type: "boolean", defaultValue: true, showInList: true, showInExport: true },
    ],
  },
  {
    key: "branches",
    label: "Branches",
    singular: "branch",
    description: "Company branches and offices.",
    icon: GitBranch,
    table: "branches",
    nameField: "name",
    orderBy: "name",
    fields: [
      { key: "code", label: "Code", type: "text", required: true, uppercase: true, showInList: true, showInExport: true },
      { key: "name", label: "Name", type: "text", required: true, showInList: true, showInExport: true },
      { key: "gstin", label: "GSTIN", type: "text", uppercase: true, showInList: true, showInExport: true },
      { key: "state_code", label: "State code", type: "text", showInList: true, showInExport: true },
      { key: "address", label: "Address", type: "textarea", span: 2, showInExport: true },
      { key: "is_head_office", label: "Head office", type: "boolean", defaultValue: false, showInList: true, showInExport: true },
      { key: "is_active", label: "Active", type: "boolean", defaultValue: true, showInList: true, showInExport: true },
    ],
  },
  {
    key: "employees",
    label: "Employees",
    singular: "employee",
    description: "Workforce records.",
    icon: UserRound,
    table: "employees",
    nameField: "full_name",
    orderBy: "full_name",
    editorRoles: ["hr"],
    fields: [
      { key: "employee_code", label: "Emp code", type: "text", required: true, uppercase: true, showInList: true, showInExport: true },
      { key: "full_name", label: "Full name", type: "text", required: true, showInList: true, showInExport: true, span: 2 },
      { key: "email", label: "Email", type: "email", showInList: true, showInExport: true },
      { key: "phone", label: "Phone", type: "phone", showInList: true, showInExport: true },
      { key: "designation", label: "Designation", type: "text", showInList: true, showInExport: true },
      { key: "department", label: "Department", type: "text", showInList: true, showInExport: true },
      { key: "date_of_joining", label: "Date of joining", type: "date", required: true, showInList: true, showInExport: true },
      { key: "date_of_birth", label: "Date of birth", type: "date", showInExport: true },
    ],
  },
];

export function getMaster(key: string): MasterDef | undefined {
  return MASTERS.find((m) => m.key === key);
}