/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated.app'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated.admin'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated.app.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated.admin.index'
import { Route as AuthenticatedAppUsersRouteImport } from './routes/_authenticated.app.users'
import { Route as AuthenticatedAppSalesRouteImport } from './routes/_authenticated.app.sales'
import { Route as AuthenticatedAppProductionRouteImport } from './routes/_authenticated.app.production'
import { Route as AuthenticatedAppProcurementRouteImport } from './routes/_authenticated.app.procurement'
import { Route as AuthenticatedAppInventoryRouteImport } from './routes/_authenticated.app.inventory'
import { Route as AuthenticatedAppFinanceRouteImport } from './routes/_authenticated.app.finance'
import { Route as AuthenticatedAppModuleRouteImport } from './routes/_authenticated.app.$module'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated.admin.users'
import { Route as AuthenticatedAppSalesIndexRouteImport } from './routes/_authenticated.app.sales.index'
import { Route as AuthenticatedAppProductionIndexRouteImport } from './routes/_authenticated.app.production.index'
import { Route as AuthenticatedAppProcurementIndexRouteImport } from './routes/_authenticated.app.procurement.index'
import { Route as AuthenticatedAppInventoryIndexRouteImport } from './routes/_authenticated.app.inventory.index'
import { Route as AuthenticatedAppFinanceIndexRouteImport } from './routes/_authenticated.app.finance.index'
import { Route as AuthenticatedAppSalesQuotationsRouteImport } from './routes/_authenticated.app.sales.quotations'
import { Route as AuthenticatedAppSalesPipelineRouteImport } from './routes/_authenticated.app.sales.pipeline'
import { Route as AuthenticatedAppSalesOrdersRouteImport } from './routes/_authenticated.app.sales.orders'
import { Route as AuthenticatedAppSalesInvoicesRouteImport } from './routes/_authenticated.app.sales.invoices'
import { Route as AuthenticatedAppSalesCustomersRouteImport } from './routes/_authenticated.app.sales.customers'
import { Route as AuthenticatedAppProductionWorkOrdersRouteImport } from './routes/_authenticated.app.production.work-orders'
import { Route as AuthenticatedAppProductionTimelineRouteImport } from './routes/_authenticated.app.production.timeline'
import { Route as AuthenticatedAppProductionBomsRouteImport } from './routes/_authenticated.app.production.boms'
import { Route as AuthenticatedAppProcurementSuppliersRouteImport } from './routes/_authenticated.app.procurement.suppliers'
import { Route as AuthenticatedAppProcurementRfqsRouteImport } from './routes/_authenticated.app.procurement.rfqs'
import { Route as AuthenticatedAppProcurementPurchaseOrdersRouteImport } from './routes/_authenticated.app.procurement.purchase-orders'
import { Route as AuthenticatedAppProcurementInvoicesRouteImport } from './routes/_authenticated.app.procurement.invoices'
import { Route as AuthenticatedAppProcurementIndentsRouteImport } from './routes/_authenticated.app.procurement.indents'
import { Route as AuthenticatedAppProcurementGrnsRouteImport } from './routes/_authenticated.app.procurement.grns'
import { Route as AuthenticatedAppInventoryWarehousesRouteImport } from './routes/_authenticated.app.inventory.warehouses'
import { Route as AuthenticatedAppInventoryMovementsRouteImport } from './routes/_authenticated.app.inventory.movements'
import { Route as AuthenticatedAppInventoryItemsRouteImport } from './routes/_authenticated.app.inventory.items'
import { Route as AuthenticatedAppFinanceReportsRouteImport } from './routes/_authenticated.app.finance.reports'
import { Route as AuthenticatedAppFinanceLedgerRouteImport } from './routes/_authenticated.app.finance.ledger'
import { Route as AuthenticatedAppFinanceGstRouteImport } from './routes/_authenticated.app.finance.gst'
import { Route as AuthenticatedAppFinanceAccountsRouteImport } from './routes/_authenticated.app.finance.accounts'
import { Route as AuthenticatedAppProductionWorkOrdersIdRouteImport } from './routes/_authenticated.app.production.work-orders.$id'
import { Route as AuthenticatedAppProductionBomsIdRouteImport } from './routes/_authenticated.app.production.boms.$id'
import { Route as AuthenticatedAppProcurementPurchaseOrdersIdRouteImport } from './routes/_authenticated.app.procurement.purchase-orders.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAppUsersRoute = AuthenticatedAppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppSalesRoute = AuthenticatedAppSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppProductionRoute =
  AuthenticatedAppProductionRouteImport.update({
    id: '/production',
    path: '/production',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppProcurementRoute =
  AuthenticatedAppProcurementRouteImport.update({
    id: '/procurement',
    path: '/procurement',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppInventoryRoute =
  AuthenticatedAppInventoryRouteImport.update({
    id: '/inventory',
    path: '/inventory',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppFinanceRoute = AuthenticatedAppFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppModuleRoute = AuthenticatedAppModuleRouteImport.update({
  id: '/$module',
  path: '/$module',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAppSalesIndexRoute =
  AuthenticatedAppSalesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppSalesRoute,
  } as any)
const AuthenticatedAppProductionIndexRoute =
  AuthenticatedAppProductionIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppProductionRoute,
  } as any)
const AuthenticatedAppProcurementIndexRoute =
  AuthenticatedAppProcurementIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppProcurementRoute,
  } as any)
const AuthenticatedAppInventoryIndexRoute =
  AuthenticatedAppInventoryIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppInventoryRoute,
  } as any)
const AuthenticatedAppFinanceIndexRoute =
  AuthenticatedAppFinanceIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppFinanceRoute,
  } as any)
const AuthenticatedAppSalesQuotationsRoute =
  AuthenticatedAppSalesQuotationsRouteImport.update({
    id: '/quotations',
    path: '/quotations',
    getParentRoute: () => AuthenticatedAppSalesRoute,
  } as any)
const AuthenticatedAppSalesPipelineRoute =
  AuthenticatedAppSalesPipelineRouteImport.update({
    id: '/pipeline',
    path: '/pipeline',
    getParentRoute: () => AuthenticatedAppSalesRoute,
  } as any)
const AuthenticatedAppSalesOrdersRoute =
  AuthenticatedAppSalesOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => AuthenticatedAppSalesRoute,
  } as any)
const AuthenticatedAppSalesInvoicesRoute =
  AuthenticatedAppSalesInvoicesRouteImport.update({
    id: '/invoices',
    path: '/invoices',
    getParentRoute: () => AuthenticatedAppSalesRoute,
  } as any)
const AuthenticatedAppSalesCustomersRoute =
  AuthenticatedAppSalesCustomersRouteImport.update({
    id: '/customers',
    path: '/customers',
    getParentRoute: () => AuthenticatedAppSalesRoute,
  } as any)
const AuthenticatedAppProductionWorkOrdersRoute =
  AuthenticatedAppProductionWorkOrdersRouteImport.update({
    id: '/work-orders',
    path: '/work-orders',
    getParentRoute: () => AuthenticatedAppProductionRoute,
  } as any)
const AuthenticatedAppProductionTimelineRoute =
  AuthenticatedAppProductionTimelineRouteImport.update({
    id: '/timeline',
    path: '/timeline',
    getParentRoute: () => AuthenticatedAppProductionRoute,
  } as any)
const AuthenticatedAppProductionBomsRoute =
  AuthenticatedAppProductionBomsRouteImport.update({
    id: '/boms',
    path: '/boms',
    getParentRoute: () => AuthenticatedAppProductionRoute,
  } as any)
const AuthenticatedAppProcurementSuppliersRoute =
  AuthenticatedAppProcurementSuppliersRouteImport.update({
    id: '/suppliers',
    path: '/suppliers',
    getParentRoute: () => AuthenticatedAppProcurementRoute,
  } as any)
const AuthenticatedAppProcurementRfqsRoute =
  AuthenticatedAppProcurementRfqsRouteImport.update({
    id: '/rfqs',
    path: '/rfqs',
    getParentRoute: () => AuthenticatedAppProcurementRoute,
  } as any)
const AuthenticatedAppProcurementPurchaseOrdersRoute =
  AuthenticatedAppProcurementPurchaseOrdersRouteImport.update({
    id: '/purchase-orders',
    path: '/purchase-orders',
    getParentRoute: () => AuthenticatedAppProcurementRoute,
  } as any)
const AuthenticatedAppProcurementInvoicesRoute =
  AuthenticatedAppProcurementInvoicesRouteImport.update({
    id: '/invoices',
    path: '/invoices',
    getParentRoute: () => AuthenticatedAppProcurementRoute,
  } as any)
const AuthenticatedAppProcurementIndentsRoute =
  AuthenticatedAppProcurementIndentsRouteImport.update({
    id: '/indents',
    path: '/indents',
    getParentRoute: () => AuthenticatedAppProcurementRoute,
  } as any)
const AuthenticatedAppProcurementGrnsRoute =
  AuthenticatedAppProcurementGrnsRouteImport.update({
    id: '/grns',
    path: '/grns',
    getParentRoute: () => AuthenticatedAppProcurementRoute,
  } as any)
const AuthenticatedAppInventoryWarehousesRoute =
  AuthenticatedAppInventoryWarehousesRouteImport.update({
    id: '/warehouses',
    path: '/warehouses',
    getParentRoute: () => AuthenticatedAppInventoryRoute,
  } as any)
const AuthenticatedAppInventoryMovementsRoute =
  AuthenticatedAppInventoryMovementsRouteImport.update({
    id: '/movements',
    path: '/movements',
    getParentRoute: () => AuthenticatedAppInventoryRoute,
  } as any)
const AuthenticatedAppInventoryItemsRoute =
  AuthenticatedAppInventoryItemsRouteImport.update({
    id: '/items',
    path: '/items',
    getParentRoute: () => AuthenticatedAppInventoryRoute,
  } as any)
const AuthenticatedAppFinanceReportsRoute =
  AuthenticatedAppFinanceReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedAppFinanceRoute,
  } as any)
const AuthenticatedAppFinanceLedgerRoute =
  AuthenticatedAppFinanceLedgerRouteImport.update({
    id: '/ledger',
    path: '/ledger',
    getParentRoute: () => AuthenticatedAppFinanceRoute,
  } as any)
const AuthenticatedAppFinanceGstRoute =
  AuthenticatedAppFinanceGstRouteImport.update({
    id: '/gst',
    path: '/gst',
    getParentRoute: () => AuthenticatedAppFinanceRoute,
  } as any)
const AuthenticatedAppFinanceAccountsRoute =
  AuthenticatedAppFinanceAccountsRouteImport.update({
    id: '/accounts',
    path: '/accounts',
    getParentRoute: () => AuthenticatedAppFinanceRoute,
  } as any)
const AuthenticatedAppProductionWorkOrdersIdRoute =
  AuthenticatedAppProductionWorkOrdersIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAppProductionWorkOrdersRoute,
  } as any)
const AuthenticatedAppProductionBomsIdRoute =
  AuthenticatedAppProductionBomsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAppProductionBomsRoute,
  } as any)
const AuthenticatedAppProcurementPurchaseOrdersIdRoute =
  AuthenticatedAppProcurementPurchaseOrdersIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAppProcurementPurchaseOrdersRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/app/$module': typeof AuthenticatedAppModuleRoute
  '/app/finance': typeof AuthenticatedAppFinanceRouteWithChildren
  '/app/inventory': typeof AuthenticatedAppInventoryRouteWithChildren
  '/app/procurement': typeof AuthenticatedAppProcurementRouteWithChildren
  '/app/production': typeof AuthenticatedAppProductionRouteWithChildren
  '/app/sales': typeof AuthenticatedAppSalesRouteWithChildren
  '/app/users': typeof AuthenticatedAppUsersRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/finance/accounts': typeof AuthenticatedAppFinanceAccountsRoute
  '/app/finance/gst': typeof AuthenticatedAppFinanceGstRoute
  '/app/finance/ledger': typeof AuthenticatedAppFinanceLedgerRoute
  '/app/finance/reports': typeof AuthenticatedAppFinanceReportsRoute
  '/app/inventory/items': typeof AuthenticatedAppInventoryItemsRoute
  '/app/inventory/movements': typeof AuthenticatedAppInventoryMovementsRoute
  '/app/inventory/warehouses': typeof AuthenticatedAppInventoryWarehousesRoute
  '/app/procurement/grns': typeof AuthenticatedAppProcurementGrnsRoute
  '/app/procurement/indents': typeof AuthenticatedAppProcurementIndentsRoute
  '/app/procurement/invoices': typeof AuthenticatedAppProcurementInvoicesRoute
  '/app/procurement/purchase-orders': typeof AuthenticatedAppProcurementPurchaseOrdersRouteWithChildren
  '/app/procurement/rfqs': typeof AuthenticatedAppProcurementRfqsRoute
  '/app/procurement/suppliers': typeof AuthenticatedAppProcurementSuppliersRoute
  '/app/production/boms': typeof AuthenticatedAppProductionBomsRouteWithChildren
  '/app/production/timeline': typeof AuthenticatedAppProductionTimelineRoute
  '/app/production/work-orders': typeof AuthenticatedAppProductionWorkOrdersRouteWithChildren
  '/app/sales/customers': typeof AuthenticatedAppSalesCustomersRoute
  '/app/sales/invoices': typeof AuthenticatedAppSalesInvoicesRoute
  '/app/sales/orders': typeof AuthenticatedAppSalesOrdersRoute
  '/app/sales/pipeline': typeof AuthenticatedAppSalesPipelineRoute
  '/app/sales/quotations': typeof AuthenticatedAppSalesQuotationsRoute
  '/app/finance/': typeof AuthenticatedAppFinanceIndexRoute
  '/app/inventory/': typeof AuthenticatedAppInventoryIndexRoute
  '/app/procurement/': typeof AuthenticatedAppProcurementIndexRoute
  '/app/production/': typeof AuthenticatedAppProductionIndexRoute
  '/app/sales/': typeof AuthenticatedAppSalesIndexRoute
  '/app/procurement/purchase-orders/$id': typeof AuthenticatedAppProcurementPurchaseOrdersIdRoute
  '/app/production/boms/$id': typeof AuthenticatedAppProductionBomsIdRoute
  '/app/production/work-orders/$id': typeof AuthenticatedAppProductionWorkOrdersIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/app/$module': typeof AuthenticatedAppModuleRoute
  '/app/users': typeof AuthenticatedAppUsersRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/finance/accounts': typeof AuthenticatedAppFinanceAccountsRoute
  '/app/finance/gst': typeof AuthenticatedAppFinanceGstRoute
  '/app/finance/ledger': typeof AuthenticatedAppFinanceLedgerRoute
  '/app/finance/reports': typeof AuthenticatedAppFinanceReportsRoute
  '/app/inventory/items': typeof AuthenticatedAppInventoryItemsRoute
  '/app/inventory/movements': typeof AuthenticatedAppInventoryMovementsRoute
  '/app/inventory/warehouses': typeof AuthenticatedAppInventoryWarehousesRoute
  '/app/procurement/grns': typeof AuthenticatedAppProcurementGrnsRoute
  '/app/procurement/indents': typeof AuthenticatedAppProcurementIndentsRoute
  '/app/procurement/invoices': typeof AuthenticatedAppProcurementInvoicesRoute
  '/app/procurement/purchase-orders': typeof AuthenticatedAppProcurementPurchaseOrdersRouteWithChildren
  '/app/procurement/rfqs': typeof AuthenticatedAppProcurementRfqsRoute
  '/app/procurement/suppliers': typeof AuthenticatedAppProcurementSuppliersRoute
  '/app/production/boms': typeof AuthenticatedAppProductionBomsRouteWithChildren
  '/app/production/timeline': typeof AuthenticatedAppProductionTimelineRoute
  '/app/production/work-orders': typeof AuthenticatedAppProductionWorkOrdersRouteWithChildren
  '/app/sales/customers': typeof AuthenticatedAppSalesCustomersRoute
  '/app/sales/invoices': typeof AuthenticatedAppSalesInvoicesRoute
  '/app/sales/orders': typeof AuthenticatedAppSalesOrdersRoute
  '/app/sales/pipeline': typeof AuthenticatedAppSalesPipelineRoute
  '/app/sales/quotations': typeof AuthenticatedAppSalesQuotationsRoute
  '/app/finance': typeof AuthenticatedAppFinanceIndexRoute
  '/app/inventory': typeof AuthenticatedAppInventoryIndexRoute
  '/app/procurement': typeof AuthenticatedAppProcurementIndexRoute
  '/app/production': typeof AuthenticatedAppProductionIndexRoute
  '/app/sales': typeof AuthenticatedAppSalesIndexRoute
  '/app/procurement/purchase-orders/$id': typeof AuthenticatedAppProcurementPurchaseOrdersIdRoute
  '/app/production/boms/$id': typeof AuthenticatedAppProductionBomsIdRoute
  '/app/production/work-orders/$id': typeof AuthenticatedAppProductionWorkOrdersIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/app/$module': typeof AuthenticatedAppModuleRoute
  '/_authenticated/app/finance': typeof AuthenticatedAppFinanceRouteWithChildren
  '/_authenticated/app/inventory': typeof AuthenticatedAppInventoryRouteWithChildren
  '/_authenticated/app/procurement': typeof AuthenticatedAppProcurementRouteWithChildren
  '/_authenticated/app/production': typeof AuthenticatedAppProductionRouteWithChildren
  '/_authenticated/app/sales': typeof AuthenticatedAppSalesRouteWithChildren
  '/_authenticated/app/users': typeof AuthenticatedAppUsersRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/finance/accounts': typeof AuthenticatedAppFinanceAccountsRoute
  '/_authenticated/app/finance/gst': typeof AuthenticatedAppFinanceGstRoute
  '/_authenticated/app/finance/ledger': typeof AuthenticatedAppFinanceLedgerRoute
  '/_authenticated/app/finance/reports': typeof AuthenticatedAppFinanceReportsRoute
  '/_authenticated/app/inventory/items': typeof AuthenticatedAppInventoryItemsRoute
  '/_authenticated/app/inventory/movements': typeof AuthenticatedAppInventoryMovementsRoute
  '/_authenticated/app/inventory/warehouses': typeof AuthenticatedAppInventoryWarehousesRoute
  '/_authenticated/app/procurement/grns': typeof AuthenticatedAppProcurementGrnsRoute
  '/_authenticated/app/procurement/indents': typeof AuthenticatedAppProcurementIndentsRoute
  '/_authenticated/app/procurement/invoices': typeof AuthenticatedAppProcurementInvoicesRoute
  '/_authenticated/app/procurement/purchase-orders': typeof AuthenticatedAppProcurementPurchaseOrdersRouteWithChildren
  '/_authenticated/app/procurement/rfqs': typeof AuthenticatedAppProcurementRfqsRoute
  '/_authenticated/app/procurement/suppliers': typeof AuthenticatedAppProcurementSuppliersRoute
  '/_authenticated/app/production/boms': typeof AuthenticatedAppProductionBomsRouteWithChildren
  '/_authenticated/app/production/timeline': typeof AuthenticatedAppProductionTimelineRoute
  '/_authenticated/app/production/work-orders': typeof AuthenticatedAppProductionWorkOrdersRouteWithChildren
  '/_authenticated/app/sales/customers': typeof AuthenticatedAppSalesCustomersRoute
  '/_authenticated/app/sales/invoices': typeof AuthenticatedAppSalesInvoicesRoute
  '/_authenticated/app/sales/orders': typeof AuthenticatedAppSalesOrdersRoute
  '/_authenticated/app/sales/pipeline': typeof AuthenticatedAppSalesPipelineRoute
  '/_authenticated/app/sales/quotations': typeof AuthenticatedAppSalesQuotationsRoute
  '/_authenticated/app/finance/': typeof AuthenticatedAppFinanceIndexRoute
  '/_authenticated/app/inventory/': typeof AuthenticatedAppInventoryIndexRoute
  '/_authenticated/app/procurement/': typeof AuthenticatedAppProcurementIndexRoute
  '/_authenticated/app/production/': typeof AuthenticatedAppProductionIndexRoute
  '/_authenticated/app/sales/': typeof AuthenticatedAppSalesIndexRoute
  '/_authenticated/app/procurement/purchase-orders/$id': typeof AuthenticatedAppProcurementPurchaseOrdersIdRoute
  '/_authenticated/app/production/boms/$id': typeof AuthenticatedAppProductionBomsIdRoute
  '/_authenticated/app/production/work-orders/$id': typeof AuthenticatedAppProductionWorkOrdersIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin'
    | '/app'
    | '/admin/users'
    | '/app/$module'
    | '/app/finance'
    | '/app/inventory'
    | '/app/procurement'
    | '/app/production'
    | '/app/sales'
    | '/app/users'
    | '/admin/'
    | '/app/'
    | '/app/finance/accounts'
    | '/app/finance/gst'
    | '/app/finance/ledger'
    | '/app/finance/reports'
    | '/app/inventory/items'
    | '/app/inventory/movements'
    | '/app/inventory/warehouses'
    | '/app/procurement/grns'
    | '/app/procurement/indents'
    | '/app/procurement/invoices'
    | '/app/procurement/purchase-orders'
    | '/app/procurement/rfqs'
    | '/app/procurement/suppliers'
    | '/app/production/boms'
    | '/app/production/timeline'
    | '/app/production/work-orders'
    | '/app/sales/customers'
    | '/app/sales/invoices'
    | '/app/sales/orders'
    | '/app/sales/pipeline'
    | '/app/sales/quotations'
    | '/app/finance/'
    | '/app/inventory/'
    | '/app/procurement/'
    | '/app/production/'
    | '/app/sales/'
    | '/app/procurement/purchase-orders/$id'
    | '/app/production/boms/$id'
    | '/app/production/work-orders/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/users'
    | '/app/$module'
    | '/app/users'
    | '/admin'
    | '/app'
    | '/app/finance/accounts'
    | '/app/finance/gst'
    | '/app/finance/ledger'
    | '/app/finance/reports'
    | '/app/inventory/items'
    | '/app/inventory/movements'
    | '/app/inventory/warehouses'
    | '/app/procurement/grns'
    | '/app/procurement/indents'
    | '/app/procurement/invoices'
    | '/app/procurement/purchase-orders'
    | '/app/procurement/rfqs'
    | '/app/procurement/suppliers'
    | '/app/production/boms'
    | '/app/production/timeline'
    | '/app/production/work-orders'
    | '/app/sales/customers'
    | '/app/sales/invoices'
    | '/app/sales/orders'
    | '/app/sales/pipeline'
    | '/app/sales/quotations'
    | '/app/finance'
    | '/app/inventory'
    | '/app/procurement'
    | '/app/production'
    | '/app/sales'
    | '/app/procurement/purchase-orders/$id'
    | '/app/production/boms/$id'
    | '/app/production/work-orders/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/admin'
    | '/_authenticated/app'
    | '/_authenticated/admin/users'
    | '/_authenticated/app/$module'
    | '/_authenticated/app/finance'
    | '/_authenticated/app/inventory'
    | '/_authenticated/app/procurement'
    | '/_authenticated/app/production'
    | '/_authenticated/app/sales'
    | '/_authenticated/app/users'
    | '/_authenticated/admin/'
    | '/_authenticated/app/'
    | '/_authenticated/app/finance/accounts'
    | '/_authenticated/app/finance/gst'
    | '/_authenticated/app/finance/ledger'
    | '/_authenticated/app/finance/reports'
    | '/_authenticated/app/inventory/items'
    | '/_authenticated/app/inventory/movements'
    | '/_authenticated/app/inventory/warehouses'
    | '/_authenticated/app/procurement/grns'
    | '/_authenticated/app/procurement/indents'
    | '/_authenticated/app/procurement/invoices'
    | '/_authenticated/app/procurement/purchase-orders'
    | '/_authenticated/app/procurement/rfqs'
    | '/_authenticated/app/procurement/suppliers'
    | '/_authenticated/app/production/boms'
    | '/_authenticated/app/production/timeline'
    | '/_authenticated/app/production/work-orders'
    | '/_authenticated/app/sales/customers'
    | '/_authenticated/app/sales/invoices'
    | '/_authenticated/app/sales/orders'
    | '/_authenticated/app/sales/pipeline'
    | '/_authenticated/app/sales/quotations'
    | '/_authenticated/app/finance/'
    | '/_authenticated/app/inventory/'
    | '/_authenticated/app/procurement/'
    | '/_authenticated/app/production/'
    | '/_authenticated/app/sales/'
    | '/_authenticated/app/procurement/purchase-orders/$id'
    | '/_authenticated/app/production/boms/$id'
    | '/_authenticated/app/production/work-orders/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/app/users': {
      id: '/_authenticated/app/users'
      path: '/users'
      fullPath: '/app/users'
      preLoaderRoute: typeof AuthenticatedAppUsersRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/sales': {
      id: '/_authenticated/app/sales'
      path: '/sales'
      fullPath: '/app/sales'
      preLoaderRoute: typeof AuthenticatedAppSalesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/production': {
      id: '/_authenticated/app/production'
      path: '/production'
      fullPath: '/app/production'
      preLoaderRoute: typeof AuthenticatedAppProductionRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/procurement': {
      id: '/_authenticated/app/procurement'
      path: '/procurement'
      fullPath: '/app/procurement'
      preLoaderRoute: typeof AuthenticatedAppProcurementRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/inventory': {
      id: '/_authenticated/app/inventory'
      path: '/inventory'
      fullPath: '/app/inventory'
      preLoaderRoute: typeof AuthenticatedAppInventoryRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/finance': {
      id: '/_authenticated/app/finance'
      path: '/finance'
      fullPath: '/app/finance'
      preLoaderRoute: typeof AuthenticatedAppFinanceRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/$module': {
      id: '/_authenticated/app/$module'
      path: '/$module'
      fullPath: '/app/$module'
      preLoaderRoute: typeof AuthenticatedAppModuleRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/app/sales/': {
      id: '/_authenticated/app/sales/'
      path: '/'
      fullPath: '/app/sales/'
      preLoaderRoute: typeof AuthenticatedAppSalesIndexRouteImport
      parentRoute: typeof AuthenticatedAppSalesRoute
    }
    '/_authenticated/app/production/': {
      id: '/_authenticated/app/production/'
      path: '/'
      fullPath: '/app/production/'
      preLoaderRoute: typeof AuthenticatedAppProductionIndexRouteImport
      parentRoute: typeof AuthenticatedAppProductionRoute
    }
    '/_authenticated/app/procurement/': {
      id: '/_authenticated/app/procurement/'
      path: '/'
      fullPath: '/app/procurement/'
      preLoaderRoute: typeof AuthenticatedAppProcurementIndexRouteImport
      parentRoute: typeof AuthenticatedAppProcurementRoute
    }
    '/_authenticated/app/inventory/': {
      id: '/_authenticated/app/inventory/'
      path: '/'
      fullPath: '/app/inventory/'
      preLoaderRoute: typeof AuthenticatedAppInventoryIndexRouteImport
      parentRoute: typeof AuthenticatedAppInventoryRoute
    }
    '/_authenticated/app/finance/': {
      id: '/_authenticated/app/finance/'
      path: '/'
      fullPath: '/app/finance/'
      preLoaderRoute: typeof AuthenticatedAppFinanceIndexRouteImport
      parentRoute: typeof AuthenticatedAppFinanceRoute
    }
    '/_authenticated/app/sales/quotations': {
      id: '/_authenticated/app/sales/quotations'
      path: '/quotations'
      fullPath: '/app/sales/quotations'
      preLoaderRoute: typeof AuthenticatedAppSalesQuotationsRouteImport
      parentRoute: typeof AuthenticatedAppSalesRoute
    }
    '/_authenticated/app/sales/pipeline': {
      id: '/_authenticated/app/sales/pipeline'
      path: '/pipeline'
      fullPath: '/app/sales/pipeline'
      preLoaderRoute: typeof AuthenticatedAppSalesPipelineRouteImport
      parentRoute: typeof AuthenticatedAppSalesRoute
    }
    '/_authenticated/app/sales/orders': {
      id: '/_authenticated/app/sales/orders'
      path: '/orders'
      fullPath: '/app/sales/orders'
      preLoaderRoute: typeof AuthenticatedAppSalesOrdersRouteImport
      parentRoute: typeof AuthenticatedAppSalesRoute
    }
    '/_authenticated/app/sales/invoices': {
      id: '/_authenticated/app/sales/invoices'
      path: '/invoices'
      fullPath: '/app/sales/invoices'
      preLoaderRoute: typeof AuthenticatedAppSalesInvoicesRouteImport
      parentRoute: typeof AuthenticatedAppSalesRoute
    }
    '/_authenticated/app/sales/customers': {
      id: '/_authenticated/app/sales/customers'
      path: '/customers'
      fullPath: '/app/sales/customers'
      preLoaderRoute: typeof AuthenticatedAppSalesCustomersRouteImport
      parentRoute: typeof AuthenticatedAppSalesRoute
    }
    '/_authenticated/app/production/work-orders': {
      id: '/_authenticated/app/production/work-orders'
      path: '/work-orders'
      fullPath: '/app/production/work-orders'
      preLoaderRoute: typeof AuthenticatedAppProductionWorkOrdersRouteImport
      parentRoute: typeof AuthenticatedAppProductionRoute
    }
    '/_authenticated/app/production/timeline': {
      id: '/_authenticated/app/production/timeline'
      path: '/timeline'
      fullPath: '/app/production/timeline'
      preLoaderRoute: typeof AuthenticatedAppProductionTimelineRouteImport
      parentRoute: typeof AuthenticatedAppProductionRoute
    }
    '/_authenticated/app/production/boms': {
      id: '/_authenticated/app/production/boms'
      path: '/boms'
      fullPath: '/app/production/boms'
      preLoaderRoute: typeof AuthenticatedAppProductionBomsRouteImport
      parentRoute: typeof AuthenticatedAppProductionRoute
    }
    '/_authenticated/app/procurement/suppliers': {
      id: '/_authenticated/app/procurement/suppliers'
      path: '/suppliers'
      fullPath: '/app/procurement/suppliers'
      preLoaderRoute: typeof AuthenticatedAppProcurementSuppliersRouteImport
      parentRoute: typeof AuthenticatedAppProcurementRoute
    }
    '/_authenticated/app/procurement/rfqs': {
      id: '/_authenticated/app/procurement/rfqs'
      path: '/rfqs'
      fullPath: '/app/procurement/rfqs'
      preLoaderRoute: typeof AuthenticatedAppProcurementRfqsRouteImport
      parentRoute: typeof AuthenticatedAppProcurementRoute
    }
    '/_authenticated/app/procurement/purchase-orders': {
      id: '/_authenticated/app/procurement/purchase-orders'
      path: '/purchase-orders'
      fullPath: '/app/procurement/purchase-orders'
      preLoaderRoute: typeof AuthenticatedAppProcurementPurchaseOrdersRouteImport
      parentRoute: typeof AuthenticatedAppProcurementRoute
    }
    '/_authenticated/app/procurement/invoices': {
      id: '/_authenticated/app/procurement/invoices'
      path: '/invoices'
      fullPath: '/app/procurement/invoices'
      preLoaderRoute: typeof AuthenticatedAppProcurementInvoicesRouteImport
      parentRoute: typeof AuthenticatedAppProcurementRoute
    }
    '/_authenticated/app/procurement/indents': {
      id: '/_authenticated/app/procurement/indents'
      path: '/indents'
      fullPath: '/app/procurement/indents'
      preLoaderRoute: typeof AuthenticatedAppProcurementIndentsRouteImport
      parentRoute: typeof AuthenticatedAppProcurementRoute
    }
    '/_authenticated/app/procurement/grns': {
      id: '/_authenticated/app/procurement/grns'
      path: '/grns'
      fullPath: '/app/procurement/grns'
      preLoaderRoute: typeof AuthenticatedAppProcurementGrnsRouteImport
      parentRoute: typeof AuthenticatedAppProcurementRoute
    }
    '/_authenticated/app/inventory/warehouses': {
      id: '/_authenticated/app/inventory/warehouses'
      path: '/warehouses'
      fullPath: '/app/inventory/warehouses'
      preLoaderRoute: typeof AuthenticatedAppInventoryWarehousesRouteImport
      parentRoute: typeof AuthenticatedAppInventoryRoute
    }
    '/_authenticated/app/inventory/movements': {
      id: '/_authenticated/app/inventory/movements'
      path: '/movements'
      fullPath: '/app/inventory/movements'
      preLoaderRoute: typeof AuthenticatedAppInventoryMovementsRouteImport
      parentRoute: typeof AuthenticatedAppInventoryRoute
    }
    '/_authenticated/app/inventory/items': {
      id: '/_authenticated/app/inventory/items'
      path: '/items'
      fullPath: '/app/inventory/items'
      preLoaderRoute: typeof AuthenticatedAppInventoryItemsRouteImport
      parentRoute: typeof AuthenticatedAppInventoryRoute
    }
    '/_authenticated/app/finance/reports': {
      id: '/_authenticated/app/finance/reports'
      path: '/reports'
      fullPath: '/app/finance/reports'
      preLoaderRoute: typeof AuthenticatedAppFinanceReportsRouteImport
      parentRoute: typeof AuthenticatedAppFinanceRoute
    }
    '/_authenticated/app/finance/ledger': {
      id: '/_authenticated/app/finance/ledger'
      path: '/ledger'
      fullPath: '/app/finance/ledger'
      preLoaderRoute: typeof AuthenticatedAppFinanceLedgerRouteImport
      parentRoute: typeof AuthenticatedAppFinanceRoute
    }
    '/_authenticated/app/finance/gst': {
      id: '/_authenticated/app/finance/gst'
      path: '/gst'
      fullPath: '/app/finance/gst'
      preLoaderRoute: typeof AuthenticatedAppFinanceGstRouteImport
      parentRoute: typeof AuthenticatedAppFinanceRoute
    }
    '/_authenticated/app/finance/accounts': {
      id: '/_authenticated/app/finance/accounts'
      path: '/accounts'
      fullPath: '/app/finance/accounts'
      preLoaderRoute: typeof AuthenticatedAppFinanceAccountsRouteImport
      parentRoute: typeof AuthenticatedAppFinanceRoute
    }
    '/_authenticated/app/production/work-orders/$id': {
      id: '/_authenticated/app/production/work-orders/$id'
      path: '/$id'
      fullPath: '/app/production/work-orders/$id'
      preLoaderRoute: typeof AuthenticatedAppProductionWorkOrdersIdRouteImport
      parentRoute: typeof AuthenticatedAppProductionWorkOrdersRoute
    }
    '/_authenticated/app/production/boms/$id': {
      id: '/_authenticated/app/production/boms/$id'
      path: '/$id'
      fullPath: '/app/production/boms/$id'
      preLoaderRoute: typeof AuthenticatedAppProductionBomsIdRouteImport
      parentRoute: typeof AuthenticatedAppProductionBomsRoute
    }
    '/_authenticated/app/procurement/purchase-orders/$id': {
      id: '/_authenticated/app/procurement/purchase-orders/$id'
      path: '/$id'
      fullPath: '/app/procurement/purchase-orders/$id'
      preLoaderRoute: typeof AuthenticatedAppProcurementPurchaseOrdersIdRouteImport
      parentRoute: typeof AuthenticatedAppProcurementPurchaseOrdersRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedAppFinanceRouteChildren {
  AuthenticatedAppFinanceAccountsRoute: typeof AuthenticatedAppFinanceAccountsRoute
  AuthenticatedAppFinanceGstRoute: typeof AuthenticatedAppFinanceGstRoute
  AuthenticatedAppFinanceLedgerRoute: typeof AuthenticatedAppFinanceLedgerRoute
  AuthenticatedAppFinanceReportsRoute: typeof AuthenticatedAppFinanceReportsRoute
  AuthenticatedAppFinanceIndexRoute: typeof AuthenticatedAppFinanceIndexRoute
}

const AuthenticatedAppFinanceRouteChildren: AuthenticatedAppFinanceRouteChildren =
  {
    AuthenticatedAppFinanceAccountsRoute: AuthenticatedAppFinanceAccountsRoute,
    AuthenticatedAppFinanceGstRoute: AuthenticatedAppFinanceGstRoute,
    AuthenticatedAppFinanceLedgerRoute: AuthenticatedAppFinanceLedgerRoute,
    AuthenticatedAppFinanceReportsRoute: AuthenticatedAppFinanceReportsRoute,
    AuthenticatedAppFinanceIndexRoute: AuthenticatedAppFinanceIndexRoute,
  }

const AuthenticatedAppFinanceRouteWithChildren =
  AuthenticatedAppFinanceRoute._addFileChildren(
    AuthenticatedAppFinanceRouteChildren,
  )

interface AuthenticatedAppInventoryRouteChildren {
  AuthenticatedAppInventoryItemsRoute: typeof AuthenticatedAppInventoryItemsRoute
  AuthenticatedAppInventoryMovementsRoute: typeof AuthenticatedAppInventoryMovementsRoute
  AuthenticatedAppInventoryWarehousesRoute: typeof AuthenticatedAppInventoryWarehousesRoute
  AuthenticatedAppInventoryIndexRoute: typeof AuthenticatedAppInventoryIndexRoute
}

const AuthenticatedAppInventoryRouteChildren: AuthenticatedAppInventoryRouteChildren =
  {
    AuthenticatedAppInventoryItemsRoute: AuthenticatedAppInventoryItemsRoute,
    AuthenticatedAppInventoryMovementsRoute:
      AuthenticatedAppInventoryMovementsRoute,
    AuthenticatedAppInventoryWarehousesRoute:
      AuthenticatedAppInventoryWarehousesRoute,
    AuthenticatedAppInventoryIndexRoute: AuthenticatedAppInventoryIndexRoute,
  }

const AuthenticatedAppInventoryRouteWithChildren =
  AuthenticatedAppInventoryRoute._addFileChildren(
    AuthenticatedAppInventoryRouteChildren,
  )

interface AuthenticatedAppProcurementPurchaseOrdersRouteChildren {
  AuthenticatedAppProcurementPurchaseOrdersIdRoute: typeof AuthenticatedAppProcurementPurchaseOrdersIdRoute
}

const AuthenticatedAppProcurementPurchaseOrdersRouteChildren: AuthenticatedAppProcurementPurchaseOrdersRouteChildren =
  {
    AuthenticatedAppProcurementPurchaseOrdersIdRoute:
      AuthenticatedAppProcurementPurchaseOrdersIdRoute,
  }

const AuthenticatedAppProcurementPurchaseOrdersRouteWithChildren =
  AuthenticatedAppProcurementPurchaseOrdersRoute._addFileChildren(
    AuthenticatedAppProcurementPurchaseOrdersRouteChildren,
  )

interface AuthenticatedAppProcurementRouteChildren {
  AuthenticatedAppProcurementGrnsRoute: typeof AuthenticatedAppProcurementGrnsRoute
  AuthenticatedAppProcurementIndentsRoute: typeof AuthenticatedAppProcurementIndentsRoute
  AuthenticatedAppProcurementInvoicesRoute: typeof AuthenticatedAppProcurementInvoicesRoute
  AuthenticatedAppProcurementPurchaseOrdersRoute: typeof AuthenticatedAppProcurementPurchaseOrdersRouteWithChildren
  AuthenticatedAppProcurementRfqsRoute: typeof AuthenticatedAppProcurementRfqsRoute
  AuthenticatedAppProcurementSuppliersRoute: typeof AuthenticatedAppProcurementSuppliersRoute
  AuthenticatedAppProcurementIndexRoute: typeof AuthenticatedAppProcurementIndexRoute
}

const AuthenticatedAppProcurementRouteChildren: AuthenticatedAppProcurementRouteChildren =
  {
    AuthenticatedAppProcurementGrnsRoute: AuthenticatedAppProcurementGrnsRoute,
    AuthenticatedAppProcurementIndentsRoute:
      AuthenticatedAppProcurementIndentsRoute,
    AuthenticatedAppProcurementInvoicesRoute:
      AuthenticatedAppProcurementInvoicesRoute,
    AuthenticatedAppProcurementPurchaseOrdersRoute:
      AuthenticatedAppProcurementPurchaseOrdersRouteWithChildren,
    AuthenticatedAppProcurementRfqsRoute: AuthenticatedAppProcurementRfqsRoute,
    AuthenticatedAppProcurementSuppliersRoute:
      AuthenticatedAppProcurementSuppliersRoute,
    AuthenticatedAppProcurementIndexRoute:
      AuthenticatedAppProcurementIndexRoute,
  }

const AuthenticatedAppProcurementRouteWithChildren =
  AuthenticatedAppProcurementRoute._addFileChildren(
    AuthenticatedAppProcurementRouteChildren,
  )

interface AuthenticatedAppProductionBomsRouteChildren {
  AuthenticatedAppProductionBomsIdRoute: typeof AuthenticatedAppProductionBomsIdRoute
}

const AuthenticatedAppProductionBomsRouteChildren: AuthenticatedAppProductionBomsRouteChildren =
  {
    AuthenticatedAppProductionBomsIdRoute:
      AuthenticatedAppProductionBomsIdRoute,
  }

const AuthenticatedAppProductionBomsRouteWithChildren =
  AuthenticatedAppProductionBomsRoute._addFileChildren(
    AuthenticatedAppProductionBomsRouteChildren,
  )

interface AuthenticatedAppProductionWorkOrdersRouteChildren {
  AuthenticatedAppProductionWorkOrdersIdRoute: typeof AuthenticatedAppProductionWorkOrdersIdRoute
}

const AuthenticatedAppProductionWorkOrdersRouteChildren: AuthenticatedAppProductionWorkOrdersRouteChildren =
  {
    AuthenticatedAppProductionWorkOrdersIdRoute:
      AuthenticatedAppProductionWorkOrdersIdRoute,
  }

const AuthenticatedAppProductionWorkOrdersRouteWithChildren =
  AuthenticatedAppProductionWorkOrdersRoute._addFileChildren(
    AuthenticatedAppProductionWorkOrdersRouteChildren,
  )

interface AuthenticatedAppProductionRouteChildren {
  AuthenticatedAppProductionBomsRoute: typeof AuthenticatedAppProductionBomsRouteWithChildren
  AuthenticatedAppProductionTimelineRoute: typeof AuthenticatedAppProductionTimelineRoute
  AuthenticatedAppProductionWorkOrdersRoute: typeof AuthenticatedAppProductionWorkOrdersRouteWithChildren
  AuthenticatedAppProductionIndexRoute: typeof AuthenticatedAppProductionIndexRoute
}

const AuthenticatedAppProductionRouteChildren: AuthenticatedAppProductionRouteChildren =
  {
    AuthenticatedAppProductionBomsRoute:
      AuthenticatedAppProductionBomsRouteWithChildren,
    AuthenticatedAppProductionTimelineRoute:
      AuthenticatedAppProductionTimelineRoute,
    AuthenticatedAppProductionWorkOrdersRoute:
      AuthenticatedAppProductionWorkOrdersRouteWithChildren,
    AuthenticatedAppProductionIndexRoute: AuthenticatedAppProductionIndexRoute,
  }

const AuthenticatedAppProductionRouteWithChildren =
  AuthenticatedAppProductionRoute._addFileChildren(
    AuthenticatedAppProductionRouteChildren,
  )

interface AuthenticatedAppSalesRouteChildren {
  AuthenticatedAppSalesCustomersRoute: typeof AuthenticatedAppSalesCustomersRoute
  AuthenticatedAppSalesInvoicesRoute: typeof AuthenticatedAppSalesInvoicesRoute
  AuthenticatedAppSalesOrdersRoute: typeof AuthenticatedAppSalesOrdersRoute
  AuthenticatedAppSalesPipelineRoute: typeof AuthenticatedAppSalesPipelineRoute
  AuthenticatedAppSalesQuotationsRoute: typeof AuthenticatedAppSalesQuotationsRoute
  AuthenticatedAppSalesIndexRoute: typeof AuthenticatedAppSalesIndexRoute
}

const AuthenticatedAppSalesRouteChildren: AuthenticatedAppSalesRouteChildren = {
  AuthenticatedAppSalesCustomersRoute: AuthenticatedAppSalesCustomersRoute,
  AuthenticatedAppSalesInvoicesRoute: AuthenticatedAppSalesInvoicesRoute,
  AuthenticatedAppSalesOrdersRoute: AuthenticatedAppSalesOrdersRoute,
  AuthenticatedAppSalesPipelineRoute: AuthenticatedAppSalesPipelineRoute,
  AuthenticatedAppSalesQuotationsRoute: AuthenticatedAppSalesQuotationsRoute,
  AuthenticatedAppSalesIndexRoute: AuthenticatedAppSalesIndexRoute,
}

const AuthenticatedAppSalesRouteWithChildren =
  AuthenticatedAppSalesRoute._addFileChildren(
    AuthenticatedAppSalesRouteChildren,
  )

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppModuleRoute: typeof AuthenticatedAppModuleRoute
  AuthenticatedAppFinanceRoute: typeof AuthenticatedAppFinanceRouteWithChildren
  AuthenticatedAppInventoryRoute: typeof AuthenticatedAppInventoryRouteWithChildren
  AuthenticatedAppProcurementRoute: typeof AuthenticatedAppProcurementRouteWithChildren
  AuthenticatedAppProductionRoute: typeof AuthenticatedAppProductionRouteWithChildren
  AuthenticatedAppSalesRoute: typeof AuthenticatedAppSalesRouteWithChildren
  AuthenticatedAppUsersRoute: typeof AuthenticatedAppUsersRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppModuleRoute: AuthenticatedAppModuleRoute,
  AuthenticatedAppFinanceRoute: AuthenticatedAppFinanceRouteWithChildren,
  AuthenticatedAppInventoryRoute: AuthenticatedAppInventoryRouteWithChildren,
  AuthenticatedAppProcurementRoute:
    AuthenticatedAppProcurementRouteWithChildren,
  AuthenticatedAppProductionRoute: AuthenticatedAppProductionRouteWithChildren,
  AuthenticatedAppSalesRoute: AuthenticatedAppSalesRouteWithChildren,
  AuthenticatedAppUsersRoute: AuthenticatedAppUsersRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
